@startuml
set namespaceSeparator ::

class "find_my_subway::home_screen_navi.dart::HomeScr" {
  +State<HomeScr> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "find_my_subway::home_screen_navi.dart::HomeScr"

class "find_my_subway::home_screen_navi.dart::_HomeScrState" {
  -int _curPage
  -List<Widget> _widgetPages
  -void _onTapPageChange()
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "find_my_subway::home_screen_navi.dart::_HomeScrState"

class "find_my_subway::firebase_options.dart::DefaultFirebaseOptions" {
  {static} +FirebaseOptions web
  {static} +FirebaseOptions android
  {static} +FirebaseOptions ios
  {static} +FirebaseOptions currentPlatform
}

"find_my_subway::firebase_options.dart::DefaultFirebaseOptions" o-- "firebase_core_platform_interface::firebase_core_platform_interface.dart::FirebaseOptions"

class "find_my_subway::main.dart::MyApp" {
  {static} +ValueNotifier<ThemeMode> themeNotifier
  +State<MyApp> createState()
}

"find_my_subway::main.dart::MyApp" o-- "flutter::src::foundation::change_notifier.dart::ValueNotifier<ThemeMode>"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "find_my_subway::main.dart::MyApp"

class "find_my_subway::main.dart::_MyAppState" {
  +ThemeColors themeDatas
  +void initState()
  +Widget build()
}

"find_my_subway::main.dart::_MyAppState" o-- "find_my_subway::theme.dart::ThemeColors"
"flutter::src::widgets::framework.dart::State" <|-- "find_my_subway::main.dart::_MyAppState"

class "find_my_subway::data::data_network.dart::Network" {
  +String url
  +dynamic getJsonData()
}

class "find_my_subway::data::data_FromAPI.dart::DataFromAPI" {
  +bool verifyWebsite()
  {static} +dynamic getSubwayInfo()
  {static} +dynamic getAllStationName()
  {static} +dynamic GetCurrentLoc()
}

class "find_my_subway::data::data_provider.dart::ThemeColor" {
  +ThemeColors themeDatas
  +ThemeMode themeNotifier
  +void changeTheme()
}

"find_my_subway::data::data_provider.dart::ThemeColor" o-- "find_my_subway::theme.dart::ThemeColors"
"find_my_subway::data::data_provider.dart::ThemeColor" o-- "flutter::src::material::app.dart::ThemeMode"
"flutter::src::foundation::change_notifier.dart::ChangeNotifier" <|-- "find_my_subway::data::data_provider.dart::ThemeColor"

class "find_my_subway::data::userData.dart::UserData" {
  +int id
  +String stName
}

class "find_my_subway::data::userData.dart::UserDataAdapter" {
  +int typeId
  +int hashCode
  +UserData read()
  +void write()
  +bool ==()
}

"hive::hive.dart::TypeAdapter" <|-- "find_my_subway::data::userData.dart::UserDataAdapter"

class "find_my_subway::data::data_time_convert.dart::TimeConvertor" {
  {static} +String secToStr()
  {static} +String secToEverageStr()
}

abstract class "find_my_subway::data::hive::data_hive.dart::HiveProviderInterface" {
  +dynamic getUserDataFromHive()
  +dynamic getListFromHive()
  +dynamic insert()
  +dynamic delete()
  +dynamic reset()
}

class "find_my_subway::data::hive::data_hiveImpl.dart::HiveProvider" {
  +dynamic getUserDataFromHive()
  +dynamic getListFromHive()
  +dynamic insert()
  +dynamic delete()
  +dynamic reset()
}

"find_my_subway::data::hive::data_hive.dart::HiveProviderInterface" <|-- "find_my_subway::data::hive::data_hiveImpl.dart::HiveProvider"

class "find_my_subway::data::data_set.dart::SubwayListDataSet" {
  +List<UserData> stationList
  +List<List<List<String>>> upTrainList
  +List<List<List<String>>> downTrainList
  +List<StationInform> stData
  +Map<String, Map<int, StArrivalInfo>> stCurSituation
  +Map<String, Map<String, List<StArrivalInfo>>> stComingMsg
  +Map<String, List<String>> staInfo
  +List<List<int>> comingTrainNo
}

class "find_my_subway::data::data_set.dart::StationInform" {
  +String stCode
  +String kName
  +String eName
  +String jName
}

class "find_my_subway::data::data_set.dart::StArrivalInfo" {
  +bool exP
  +String arrival
  +String ahead
  +int stId
  +String stName
}

class "find_my_subway::data::data_set.dart::FriendData" {
  +String name
  +String station
  +int trainNo
}

class "find_my_subway::data::data_set.dart::FriendPageData" {
  +bool visible
  +int autoTimer
  +int uid
  +String cur
  +int curTrainNo
  +List<String> friendList
  +List<FriendData> friendData
}

class "find_my_subway::data::data_location.dart::Location" {
  +dynamic x
  +dynamic y
  +dynamic stName
  +dynamic getMyCurrentLocation()
}

class "find_my_subway::pages::page_whereAmI.dart::WhereAmI" {
  +State<WhereAmI> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "find_my_subway::pages::page_whereAmI.dart::WhereAmI"

class "find_my_subway::pages::page_whereAmI.dart::_WhereAmIState" {
  +dynamic loadData
  +FirebaseFirestore firestore
  -Timer _timer
  +FriendPageData friendpd
  +String? friendUid
  +void initState()
  +void autoRefresh()
  -dynamic _AddFriendPopUp()
  +Widget build()
  +dynamic friendPageLoad()
}

"find_my_subway::pages::page_whereAmI.dart::_WhereAmIState" o-- "cloud_firestore::cloud_firestore.dart::FirebaseFirestore"
"find_my_subway::pages::page_whereAmI.dart::_WhereAmIState" o-- "dart::async::Timer"
"find_my_subway::pages::page_whereAmI.dart::_WhereAmIState" o-- "find_my_subway::data::data_set.dart::FriendPageData"
"flutter::src::widgets::framework.dart::State" <|-- "find_my_subway::pages::page_whereAmI.dart::_WhereAmIState"

class "find_my_subway::pages::page_favorite.dart::FavoritePage" {
  +State<FavoritePage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "find_my_subway::pages::page_favorite.dart::FavoritePage"

class "find_my_subway::pages::page_favorite.dart::FavoritePageState" {
  +dynamic infoList
  +dynamic stationData
  +HiveProvider mainHive
  +Box<dynamic> box
  -Timer _timer
  +bool wantKeepAlive
  +void dispose()
  +void initState()
  +void autoRefresh()
  +Widget build()
}

"find_my_subway::pages::page_favorite.dart::FavoritePageState" o-- "find_my_subway::data::hive::data_hiveImpl.dart::HiveProvider"
"find_my_subway::pages::page_favorite.dart::FavoritePageState" o-- "hive::hive.dart::Box<dynamic>"
"find_my_subway::pages::page_favorite.dart::FavoritePageState" o-- "dart::async::Timer"
"flutter::src::widgets::framework.dart::State" <|-- "find_my_subway::pages::page_favorite.dart::FavoritePageState"
"flutter::src::widgets::automatic_keep_alive.dart::AutomaticKeepAliveClientMixin" <|-- "find_my_subway::pages::page_favorite.dart::FavoritePageState"

class "find_my_subway::pages::page_option.dart::OptionPage" {
  +State<OptionPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "find_my_subway::pages::page_option.dart::OptionPage"

class "find_my_subway::pages::page_option.dart::_OptionPageState" {
  +FirebaseFirestore firestore
  +ThemeItem? selectedMenu
  +Box<dynamic> box
  -dynamic _AddFriendPopUp()
  +Widget build()
}

"find_my_subway::pages::page_option.dart::_OptionPageState" o-- "cloud_firestore::cloud_firestore.dart::FirebaseFirestore"
"find_my_subway::pages::page_option.dart::_OptionPageState" o-- "find_my_subway::pages::page_option.dart::ThemeItem"
"find_my_subway::pages::page_option.dart::_OptionPageState" o-- "hive::hive.dart::Box<dynamic>"
"flutter::src::widgets::framework.dart::State" <|-- "find_my_subway::pages::page_option.dart::_OptionPageState"

class "find_my_subway::pages::page_option.dart::ThemeItem" {
  +int index
  {static} +List<ThemeItem> values
  {static} +ThemeItem lightTheme
  {static} +ThemeItem darkTheme
  {static} +ThemeItem systemDefault
}

"find_my_subway::pages::page_option.dart::ThemeItem" o-- "find_my_subway::pages::page_option.dart::ThemeItem"
"dart::core::Enum" <|-- "find_my_subway::pages::page_option.dart::ThemeItem"

class "find_my_subway::pages::page_timer.dart::SubwayTimer" {
  +State<SubwayTimer> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "find_my_subway::pages::page_timer.dart::SubwayTimer"

class "find_my_subway::pages::page_timer.dart::_SubwayTimerState" {
  +Icon iconStartAndPause
  +String strTime
  +List<String> timeList
  +Box<dynamic> box
  +void initState()
  +Widget build()
}

"find_my_subway::pages::page_timer.dart::_SubwayTimerState" o-- "flutter::src::widgets::icon.dart::Icon"
"find_my_subway::pages::page_timer.dart::_SubwayTimerState" o-- "hive::hive.dart::Box<dynamic>"
"flutter::src::widgets::framework.dart::State" <|-- "find_my_subway::pages::page_timer.dart::_SubwayTimerState"

class "find_my_subway::widgets::widget_arrivals.dart::Arrivals" {
  +Map<dynamic, dynamic> lineIcons
  +UserData udata
  +List<List<List<String>>> upNdownTrain
  +List<int> comingTrainNo
  +HiveProvider mainHive
  +Map<String, List<String>> staInfo
  +Map<String, List<StArrivalInfo>> stCurComingMsg
  +State<Arrivals> createState()
}

"find_my_subway::widgets::widget_arrivals.dart::Arrivals" o-- "find_my_subway::data::userData.dart::UserData"
"find_my_subway::widgets::widget_arrivals.dart::Arrivals" o-- "find_my_subway::data::hive::data_hiveImpl.dart::HiveProvider"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "find_my_subway::widgets::widget_arrivals.dart::Arrivals"

class "find_my_subway::widgets::widget_arrivals.dart::_ArrivalsState" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "find_my_subway::widgets::widget_arrivals.dart::_ArrivalsState"

class "find_my_subway::widgets::widget_appbar.dart::Appbars" {
  +String titleName
  +Size preferredSize
  +Widget build()
}

"find_my_subway::widgets::widget_appbar.dart::Appbars" o-- "dart::ui::Size"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "find_my_subway::widgets::widget_appbar.dart::Appbars"
"flutter::src::widgets::preferred_size.dart::PreferredSizeWidget" <|-- "find_my_subway::widgets::widget_appbar.dart::Appbars"

class "find_my_subway::widgets::widget_appbar.dart::SearchAppbar" {
  +String titleName
  +HiveProvider mainHive
  +List<StationInform> data
  +ThemeData curTheme
  +Size preferredSize
  +Widget build()
}

"find_my_subway::widgets::widget_appbar.dart::SearchAppbar" o-- "find_my_subway::data::hive::data_hiveImpl.dart::HiveProvider"
"find_my_subway::widgets::widget_appbar.dart::SearchAppbar" o-- "flutter::src::material::theme_data.dart::ThemeData"
"find_my_subway::widgets::widget_appbar.dart::SearchAppbar" o-- "dart::ui::Size"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "find_my_subway::widgets::widget_appbar.dart::SearchAppbar"
"flutter::src::widgets::preferred_size.dart::PreferredSizeWidget" <|-- "find_my_subway::widgets::widget_appbar.dart::SearchAppbar"

class "find_my_subway::widgets::widget_arrivals::widget_line_iconImpl.dart::IconBundang" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "find_my_subway::widgets::widget_arrivals::widget_line_iconImpl.dart::IconBundang"
"find_my_subway::widgets::widget_arrivals::widget_line_icon.dart::LineIcon" <|-- "find_my_subway::widgets::widget_arrivals::widget_line_iconImpl.dart::IconBundang"

class "find_my_subway::widgets::widget_arrivals::widget_line_iconImpl.dart::SmallBundangIcon" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "find_my_subway::widgets::widget_arrivals::widget_line_iconImpl.dart::SmallBundangIcon"
"find_my_subway::widgets::widget_arrivals::widget_line_icon.dart::LineIcon" <|-- "find_my_subway::widgets::widget_arrivals::widget_line_iconImpl.dart::SmallBundangIcon"

class "find_my_subway::widgets::widget_arrivals::widget_detail_of_station.dart::StaDetail" {
  +List<List<List<String>>> upNdownTrain
  +State<StaDetail> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "find_my_subway::widgets::widget_arrivals::widget_detail_of_station.dart::StaDetail"

class "find_my_subway::widgets::widget_arrivals::widget_detail_of_station.dart::_StaDetailState" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "find_my_subway::widgets::widget_arrivals::widget_detail_of_station.dart::_StaDetailState"

class "find_my_subway::widgets::widget_arrivals::widget_new_station_name.dart::NewStationName" {
  +String stName
  +String prevName
  +String nextName
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "find_my_subway::widgets::widget_arrivals::widget_new_station_name.dart::NewStationName"

class "find_my_subway::widgets::widget_arrivals::widget_location.dart::SubwayLocationInfo" {
  +List<StationInform> stData
  +int curSt
  +Map<String, Map<int, StArrivalInfo>> stStatus
  +String subwayIcon
  +bool checkValidity()
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "find_my_subway::widgets::widget_arrivals::widget_location.dart::SubwayLocationInfo"

class "find_my_subway::widgets::widget_arrivals::widget_location.dart::NormalLine" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "find_my_subway::widgets::widget_arrivals::widget_location.dart::NormalLine"

class "find_my_subway::widgets::widget_arrivals::widget_station_name.dart::StationName" {
  +String stName
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "find_my_subway::widgets::widget_arrivals::widget_station_name.dart::StationName"

abstract class "find_my_subway::widgets::widget_arrivals::widget_line_icon.dart::LineIcon" {
  +Widget build()
}

class "find_my_subway::widgets::widget_arrivals::widget_new_detail.dart::NewStaDetail" {
  +List<List<List<String>>> upNdownTrain
  +List<int> comingTrainNo
  +Map<String, List<StArrivalInfo>> stComingMsg
  +State<NewStaDetail> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "find_my_subway::widgets::widget_arrivals::widget_new_detail.dart::NewStaDetail"

class "find_my_subway::widgets::widget_arrivals::widget_new_detail.dart::_NewStaDetailState" {
  +List<String> ahead
  +List<String> direct
  +FirebaseFirestore firestore
  +int uid
  +int cur
  +Box<dynamic> box
  +Widget build()
}

"find_my_subway::widgets::widget_arrivals::widget_new_detail.dart::_NewStaDetailState" o-- "cloud_firestore::cloud_firestore.dart::FirebaseFirestore"
"find_my_subway::widgets::widget_arrivals::widget_new_detail.dart::_NewStaDetailState" o-- "hive::hive.dart::Box<dynamic>"
"flutter::src::widgets::framework.dart::State" <|-- "find_my_subway::widgets::widget_arrivals::widget_new_detail.dart::_NewStaDetailState"

class "find_my_subway::theme.dart::ThemeColors" {
  +ThemeData dark
  +ThemeData light
}

"find_my_subway::theme.dart::ThemeColors" o-- "flutter::src::material::theme_data.dart::ThemeData"


@enduml
